package com.example.demo.domain.dto.interview;

import lombok.*;

import java.util.List;

/**
 * DTO returned to the frontend containing one interview question.
 *
 * File location: src/main/java/com/example/demo/domain/dto/interview/QuestionResponseDTO.java
 *
 * This file already exists in your project (visible in screenshot).
 * Replace its content with this complete version.
 */
@Getter
@Setter
@Data
@NoArgsConstructor
@AllArgsConstructor
public class QuestionResponseDTO {

    /** Cluster index this question belongs to (0, 1, 2 ...) */
    private int clusterId;

    /** Skills covered by this cluster */
    private List<String> skills;

    /** The interview question text */
    private String question;

    /**
     * The ideal reference answer generated by LLaMA.
     * Sent to the frontend so it can be included in the evaluate call.
     */
    private String answer;
}