spring.application.name=OpportuneBackend:)

spring.datasource.url=jdbc:postgresql://localhost:5433/opportune_db
spring.datasource.username=opportune_user
spring.datasource.password=opportune_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jwt.secret=O3mZ5xVJ1B0yP9Jmcd3H8tPqk9s7N4uT1q6w8bhsayrmeix
spring.jwt.expiration=86400000

spring.liquibase.enabled=false
rag.api.base-url=http://localhost:8001
mcq.api.base-url=http://localhost:8000

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=DEBUG

spring.output.ansi.enabled=always
logging.level.org.springframework.security=TRACE

gemini.api.key=REDACTED_GEMINI_API_KEY
