spring.application.name=OpportuneBackend:)

spring.datasource.url=jdbc:postgresql://localhost:5432/opportune_db
spring.datasource.username=opportune_user
spring.datasource.password=opportune_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jwt.secret=O3mZ5xVJ1B0yP9Jmcd3H8tPqk9s7N4uT1q6w8bhsayrmeix
spring.jwt.expiration=86400000

spring.liquibase.enabled=false